from enum import Enum


class ExpressionTypes(str, Enum):
    NEUTRAL = "Neutral"
    ANGER = "Anger"
    SADNESS = "Sadness"
    HAPPY = "Happy"
    SURPRISE = "Surprise"
    DISGUST = "Disgust"
    FEAR = "Fear"
    PLEADING = "Pleading"
    VULNERABILITY = "Vulnerability"
    DESPAIR = "Despair"
    GUILT = "Guilt"
    DISAPPOINTMENT = "Disappointment"
    EMBARRASSMENT = "Embarrassment"
    HORROR = "Horror"
    SKEPTICISM = "Skepticism"
    ANNOYANCE = "Annoyance"
    FURY = "Fury"
    SUSPICION = "Suspicion"
    REJECTION = "Rejection"
    BOREDOM = "Boredom"
    TIRED = "Tired"
    ASLEEP = "Asleep"
    CONFUSED = "Confused"
    AMAZED = "Amazed"
    EXCITED = "Excited"
